version: '3.9'
services:
  api:
    image: bmeares/meerschaum:2.1.5
    ports:
    - 8000:8000
    hostname: api
    command: start api --production --port 8000
    healthcheck:
      test:
      - CMD
      - curl
      - --fail
      - http://localhost:8000/healthcheck
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      MRSM_CONFIG: |-
        {
          "meerschaum": {
            "instance": "sql:prod",
            "api_instance": "sql:prod"
          }
        }
      MRSM_SQL_PROD: |-
        {
          "uri": "sqlite:////meerschaum/sqlite/prod.db"
        }
    restart: always
    init: true
    volumes:
    - api_root:/meerschaum

volumes:
  api_root: null
