version: '3.9'
services:
  api:
    image: bmeares/meerschaum:2.1.0
    ports:
    - 8000:8000
    hostname: api
    command: start api --production --port 8000
    healthcheck:
      test:
      - CMD
      - curl
      - --fail
      - http://localhost:8000/healthcheck
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      MRSM_SQL_MAIN: sqlite:////meerschaum/sqlite/main.db
    restart: always
    init: true
    volumes:
    - api_root:/meerschaum

volumes:
  api_root: null
