apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "meerschaum.fullname" . }}
  labels:
    {{- include "meerschaum.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "meerschaum.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "meerschaum.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - args:
            - start
            - api
            - --production
            - --port
            - "8000"
            - --debug
          env:
            - name: MRSM_CONFIG
              value: |-
            {{ .Values.meerschaum.config | nindent 16 }}
            - name: MRSM_SQL_PROD
              value: '{{ .Values.meerschaum.sql.prod }}'
          image: {{ include "meerschaum.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.meerschaum.healthcheckPath }}
              port: 8000
              httpHeaders:
                - name: Host
                  value: {{ include "meerschaum.host" . | quote }}
                {{- if eq .Values.meerschaum.protocol "https" }}
                - name: X-Forwarded-Proto
                  value: https
                {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.meerschaum.healthcheckPath }}
              port: 8000
              httpHeaders:
                - name: Host
                  value: {{ include "meerschaum.host" . | quote }}
                {{- if eq .Values.meerschaum.protocol "https" }}
                - name: X-Forwarded-Proto
                  value: https
                {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          name: {{ include "common.names.fullname" . }}
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: {{ .Values.persistence.path }}
              name: meerschaum-data
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: Always
      volumes:
        - name: meerschaum-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "common.names.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
status: {}
