apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "meerschaum.fullname" . }}
  labels:
    {{- include "meerschaum.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "meerschaum.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "meerschaum.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - start
            - api
            - --production
            - --port
            - "8000"
          env:
            - name: MRSM_SQL_MAIN
              value: sqlite:////meerschaum/sqlite/main.db
          image: {{ include "meerschaum.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.meerschaum.healthcheckPath }}
              port: 8000
              httpHeaders:
                - name: Host
                  value: {{ include "meerschaum.host" . | quote }}
                {{- if eq .Values.meerschaum.protocol "https" }}
                - name: X-Forwarded-Proto
                  value: https
                {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.meerschaum.healthcheckPath }}
              port: 8000
              httpHeaders:
                - name: Host
                  value: {{ include "meerschaum.host" . | quote }}
                {{- if eq .Values.meerschaum.protocol "https" }}
                - name: X-Forwarded-Proto
                  value: https
                {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          name: {{ include "common.names.fullname" . }}
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: {{ .Values.persistence.sqlitePath }}
              name: meerschaum-sqlite-data
            - mountPath: {{ .Values.persistence.configPath }}
              name: meerschaum-config-data
            - mountPath: {{ .Values.persistence.jobsPath }}
              name: meerschaum-jobs-data
            - mountPath: {{ .Values.persistence.logsPath }}
              name: meerschaum-logs-data
      restartPolicy: Always
      volumes:
        - name: meerschaum-sqlite-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            # claimName: "meerschaum-sqlite-data"
            claimName: {{ default (include "common.names.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: meerschaum-config-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            # claimName: "meerschaum-config-data"
            claimName: {{ default (include "common.names.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: meerschaum-jobs-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            # claimName: "meerschaum-jobs-data"
            claimName: {{ default (include "common.names.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: meerschaum-logs-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            # claimName: "meerschaum-jobs-data"
            claimName: {{ default (include "common.names.fullname" .) .Values.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
status: {}
